### ISSUE TITLE
Let's Chat ~ 

### ISSUE THREAD

**Issue by canisminor1990** [canisminor1990/canisminor1990#1]

**Comment by confusedGG** [comment]
安装kitchen主题，Stable Diffusion界面看不清，我应该如何修复呢？
![image](https://user-images.githubusercontent.com/52156872/231677171-a64687c1-430b-4dce-b7c0-a4927ecb7cb2.png)
![image](https://user-images.githubusercontent.com/52156872/231677423-647f7cb3-fee6-4b5c-a092-2b7917f49ba8.png)

**Comment by tonny1314sy** [comment]
你好老哥，我是上海一家公司的负责人，我有些商务想和您聊一下，方便加一下微信吗？15201949020，有点冒昧，不好意思
